FROM gkiar/fuzzy:ubuntu14.04-python-dipy-afq

ENV VFC_BACKENDS "libinterflop_ieee.so"

RUN rm -rf /etc/apt/sources.list.d/ &&\
    apt-get update -qqq &&\
    apt-get install -y libhdf5-dev &&\
    rm -rf /var/lib/apt/lists/

RUN pip3.6 install scipy cython &&\
    pip3.6 install nibabel matplotlib onevox boutiques dipy fury

COPY ./dipy_tracking.py /opt/dipy_tracking.py

ENV VFC_BACKENDS "libinterflop_mca.so -m rr"

ENTRYPOINT ["python3.6", "/opt/dipy_tracking.py"]
