# FROM gkiar/fuzzy-python:fuzzless
FROM pablooliveira/fuzzy-python:latest

RUN apt-get update -qqq &&\
    apt-get install -y libhdf5-dev &&\
    rm -rf /var/lib/apt/lists/

RUN pip3.6 install scipy cython &&\
    pip3.6 install nibabel matplotlib onevox boutiques &&\
    pip3.6 install dipy==0.16.0

COPY ./dipy_deterministic_tracking.py /opt/dipy_deterministic_tracking.py

ENTRYPOINT ["python3.6", "/opt/dipy_deterministic_tracking.py"]